export default {
  extends: ['eslint:all', 'plugin:@typescript-eslint/all', 'prettier'],

  rules: {
    'array-callback-return': ['error', { checkForEach: false }],
    'arrow-body-style': ['off'],
    '@typescript-eslint/await-thenable': ['warn'],
    camelcase: ['off'],
    'capitalized-comments': ['off'],
    '@typescript-eslint/class-literal-property-style': ['warn'],
    'class-methods-use-this': ['warn'],
    '@typescript-eslint/consistent-type-assertions': [
      'warn',
      { assertionStyle: 'as', objectLiteralTypeAssertions: 'never' },
    ],
    eqeqeq: ['error', 'smart'],
    '@typescript-eslint/explicit-function-return-type': ['off'],
    '@typescript-eslint/explicit-module-boundary-types': ['off'],
    'func-names': ['warn'],
    'func-style': ['off'],
    'id-denylist': ['off'],
    'id-length': ['off'],
    'id-match': ['off'],
    'line-comment-position': ['off'],
    'max-classes-per-file': ['warn'],
    'max-depth': ['warn'],
    'max-lines': ['warn'],
    'max-lines-per-function': ['warn'],
    'max-nested-callbacks': ['warn'],
    'max-params': ['warn'],
    'max-statements': ['warn'],
    '@typescript-eslint/member-ordering': ['warn'],
    'multiline-comment-style': ['off'],
    'no-alert': ['warn'],
    'no-console': ['warn', { allow: ['info', 'warn', 'error'] }],
    'no-constant-condition': ['error', { checkLoops: false }],
    'no-else-return': ['error', { allowElseIf: false }],
    'no-empty-function': ['warn'],
    'no-eq-null': ['off'],
    '@typescript-eslint/no-explicit-any': ['warn'],
    'no-inline-comments': ['off'],
    '@typescript-eslint/no-magic-numbers': [
      'warn',
      {
        ignore: [-1, 0, 1],
        ignoreArrayIndexes: true,
        ignoreDefaultValues: true,
        enforceConst: true,
        detectObjects: true,
      },
    ],
    'no-negated-condition': ['warn'],
    'no-nested-ternary': ['off'],
    'no-param-reassign': [
      'warn',
      {
        props: true,
        ignorePropertyModificationsFor: [
          'acc',
          'ctx',
          'context',
          'e',
          'req',
          'request',
          'res',
          'response',
          '$scope',
          'staticContext',
        ],
      },
    ],
    '@typescript-eslint/no-parameter-properties': ['off'],
    'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
    '@typescript-eslint/no-require-imports': ['off'],
    'no-restricted-exports': ['off'],
    'no-restricted-globals': ['off'],
    'no-restricted-imports': ['off'],
    'no-restricted-properties': ['off'],
    'no-restricted-syntax': ['off'],
    '@typescript-eslint/no-shadow': ['warn', { builtinGlobals: true, hoist: 'all' }],
    'no-ternary': ['off'],
    '@typescript-eslint/no-type-alias': ['off'],
    'no-undefined': ['off'],
    '@typescript-eslint/no-unused-vars': ['warn'],
    '@typescript-eslint/no-use-before-define': ['error', 'nofunc'],
    'no-warning-comments': ['warn'],
    'one-var': ['error', { initialized: 'never' }],
    'padding-line-between-statements': [
      'error',
      { blankLine: 'always', prev: '*', next: ['class', 'export', 'function'] },
    ],
    'prefer-arrow-callback': ['off'], // see https://github.com/prettier/eslint-config-prettier#arrow-body-style-and-prefer-arrow-callback
    'prefer-named-capture-group': ['off'],
    'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
    '@typescript-eslint/prefer-readonly-parameter-types': ['off'],
    'require-atomic-updates	': ['off'],
    'require-unicode-regexp': ['warn'],
    'sort-imports': ['off'],
    'sort-keys': ['off'],
    '@typescript-eslint/strict-boolean-expressions': ['off'],
    '@typescript-eslint/typedef': ['off'],
  },

  overrides: {
    js: {
      rules: {
        '@typescript-eslint/explicit-function-return-type': ['off'],
        '@typescript-eslint/explicit-member-accessibility': ['off'],
        '@typescript-eslint/explicit-module-boundary-types': ['off'],
        '@typescript-eslint/no-unsafe-call': ['off'],
        '@typescript-eslint/no-var-requires': ['off'],
      },
    },
    test: {
      rules: {
        'max-classes-per-file': ['off'],
        'max-depth': ['off'],
        'max-lines': ['off'],
        'max-lines-per-function': ['off'],
        'max-nested-callbacks': ['off'],
        'max-params': ['off'],
        'max-statements': ['off'],
        '@typescript-eslint/no-magic-numbers': ['off'],
      },
    },
  },
}
